version: "3.7"

services:
 
  # server:
  #   image: smeagolworms4/mqtt-explorer:browser-1.0.1
  #   volumes:
  #     - ${APP_DATA_DIR}/data:/mqttexplorer
  #   environment:
  #     - CONFIG_PATH=/mqttexplorer
  #     - HTTP_PORT=4821
  #   restart: on-failure

  # DIYHue:
  #   container_name: diyHue
  #   image: diyhue/core:latest
  #   mem_limit: 2040m
  #   cpus: 2
  #   volumes:
  #     - "/home/pi/share/diyhue:/opt/hue-emulator/config"
  #   environment:
  #     - MAC=DC:A6:32:A1:F9:E6
  #   restart: unless-stopped
  #   privileged: true
  #   network_mode: host

  
  server:
    image: diyhue/core
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/opt/hue-emulator/config
    environment:
      - MAC=DC:00:0c:29:0b:24:e7
      - IP=192.168.46.64
    mac_address: 00:0c:29:0b:24:e7
    networks:
      10_vlan:
        priority: 100
      20_internal: ~

networks:
  10_vlan:
    driver: macvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.1.1
          ip_range: 192.168.46.64/32
  20_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/30
          gateway: 172.18.0.1