services:
  code-server:
    environment:
      - PASSWORD=$APP_PASSWORD
      - PUID=0
      - PGID=0
    volumes:
      - ${UNIQUE_APP_DATA_DIR}/.bashrc:/home/coder/.bashrc
      - ${UNIQUE_APP_DATA_DIR}/.loaders:/home/coder/.loaders
      - ${UMBREL_ROOT}:/home/coder/umbrel
