version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: unique-rmfakecloud_server_1
      APP_PORT: 3689
      PROXY_AUTH_ADD: "false"

  server:
    image: ddvk/rmfakecloud:0.0.12-10-gaad1e50
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - STORAGE_URL=http://$EXTERNAL_IP:3689
      - JWT_SECRET_KEY=$RM_JWT
      - RM_TRUST_PROXY=true
      - PORT=3689
